steps:
  - label: ":python:"
    command:
      - pip install -q --no-cache-dir -r requirements.txt
        && python -m pytest tests -p no:cacheprovider
    plugins:
      docker#v1.3.0:
        image: "python:3.6"
        workdir: /app
        environment:
          - PYTHONDONTWRITEBYTECODE=1

  - label: "style"
    command:
      - --check stellar tests
    plugins:
      docker#v1.3.0:
        image: "513929068678.dkr.ecr.ap-southeast-2.amazonaws.com/black"
        workdir: /app
        entrypoint: /usr/bin/black
        environment:
          - PYTHONDONTWRITEBYTECODE=1

  - wait: ~
    continue_on_failure: true

  - label: ":console: push logs"
    command: .buildkite/pushlogs.sh "#build-bots"
