steps:
  - name: ":python:"
    command:
    - pip install --no-cache-dir -r requirements.txt
    - python -m pytest tests
    plugins:
      docker#v1.1.1:
        image: "python:3.6"
        workdir: /app
