steps:
  - name: ":python:"
    command:
    - pip install -q --no-cache-dir -r requirements.txt
    - python -m pytest tests -p no:cacheprovider
    plugins:
      docker#v1.1.1:
        image: "python:3.6"
        workdir: /app
        environment:
          - PYTHONDONTWRITEBYTECODE=1
  - name: "style"
    command:
    - pip install -q --no-cache-dir black
    - black --check stellar tests
    plugins:
      docker#v1.1.1:
        image: "python:3.6"
        workdir: /app
        environment:
          - PYTHONDONTWRITEBYTECODE=1

  - wait: ~
    continue_on_failure: true

  - label: "push logs"
    trigger: "buildkite-logger"
    async: true
    build:
      env:
        PIPELINE_SLUG: "${BUILDKITE_PIPELINE_SLUG}"
        BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
        BRANCH: "${BUILDKITE_BRANCH}"
