steps:
  - label: ":python: 3.6"
    command: ".buildkite/script.sh"
    plugins:
      docker#v3.0.1:
        image: "python:3.6"
        environment:
          - PYTHONDONTWRITEBYTECODE=1
          - GIT_BRANCH=$BUILDKITE_BRANCH
          - COVERALLS_REPO_TOKEN
          - BUILDKITE_BUILD_NUMBER
          - BUILDKITE_BRANCH
          # for coveralls-python, to send more metadata to coveralls.io
          - BUILDKITE
          - BUILDKITE_PULL_REQUEST
          - BUILDKITE_JOB_ID
    agents:
      queue: 't2medium'

  - label: ":python: 3.7.2"
    command: ".buildkite/script.sh"
    plugins:
      docker#v3.0.1:
        image: "python:3.7.2"
        environment:
          - PYTHONDONTWRITEBYTECODE=1
          - GIT_BRANCH=$BUILDKITE_BRANCH
          - COVERALLS_REPO_TOKEN
          - BUILDKITE_BUILD_NUMBER
          - BUILDKITE_BRANCH
          - AWS_LOGS_BUCKET
          - UPLOAD_PYTEST=true
    agents:
      queue: 't2medium'

  - label: "style"
    plugins:
      docker#v3.0.1:
        image: "stellargraph/black"
        command: ["--check", "stellargraph", "tests"]
        environment:
          - PYTHONDONTWRITEBYTECODE=1

  - wait: ~
    continue_on_failure: true

  - label: ":console: push logs"
    command: .buildkite/pushlogs.sh "#build-bots"
