---
name: Continuous Integration

"on":
  push:
    # only build each push to develop and master, other branches are built through pull requests
    branches: [develop, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test,demos]

      - name: Run pytest tests
        run: |
          # benchmarks on shared infrastructure like the CI machines are usually unreliable (high
          # variance), so there's no point spending too much time, hence --benchmark-disable which
          # just runs them once (as a test)
          py.test -ra tests/ --doctest-modules \
              --cov=stellargraph --cov-report=xml \
              -p no:cacheprovider --junitxml="pytest-results-${{ matrix.python-version }}.xml" \
              --benchmark-disable

      - name: Upload pytest test results
        uses: actions/upload-artifact@v1
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: pytest-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,PYTHON

  notebooks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        notebook:
          - "demos/basics/loading-networkx.ipynb"
          - "demos/basics/loading-numpy.ipynb"
          - "demos/basics/loading-pandas.ipynb"

    env:
      PYTHON_VERSION: 3.6

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test,demos]

      - name: Run notebook
        id: run_notebook
        run: |
          # papermill will replace parameters on some notebooks to make them run faster in CI
          papermill --execution-timeout=600 \
            --parameters_file "./.buildkite/notebook-parameters.yml" --log-output \
            "${{ matrix.notebook }}" "${{ matrix.notebook }}"
          notebook_name="$(basename "${{ matrix.notebook }}")"
          echo "::set-output name=notebook_name::$notebook_name"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.run_notebook.outputs.notebook_name }}
          path: ${{ matrix.notebook }}
        if: ${{ always() }}
